Repository DuendeSoftware/foss, pull requests merged in 2024-11, with the labels that each got.

#25 Readme Updates
  README.md
  access-token-management/README.md
  access-token-management/src/AccessTokenManagement.OpenIdConnect/README.md
  access-token-management/src/AccessTokenManagement/README.md
  identity-model-oidc-client/README.md
  identity-model-oidc-client/src/IdentityModel.OidcClient/README.md
  identity-model/README.md
  src.props
Labels: priority/3, impact/non-breaking

#29 Prepare GitHubActions workflows for .NET 9.
  .github/workflow-gen/Program.cs
  .github/workflow-gen/workflow-gen.csproj
  .github/workflows/access-token-management-ci.yml
  .github/workflows/access-token-management-release.yml
  .github/workflows/identity-model-ci.yml
  .github/workflows/identity-model-oidc-client-ci.yml
  .github/workflows/identity-model-oidc-client-release.yml
  .github/workflows/identity-model-release.yml
  .github/workflows/ignore-this-ci.yml
  .github/workflows/ignore-this-release.yml
Labels: priority/2, area/all

#47 Add a build target for convenient creation of local nuget packages
  .github/workflow-gen/workflow-gen.csproj
  access-token-management/samples/Directory.Build.props
  access-token-management/test/AccessTokenManagement.Tests/AccessTokenManagement.Tests.csproj
  docs/README.md
  docs/nuget/local.md
  identity-model-oidc-client/clients/Directory.Build.props
  identity-model-oidc-client/samples/Directory.Build.props
  identity-model/src/TrimmableAnalysis/TrimmableAnalysis.csproj
  samples.props
  src.props
  test.props
Labels: priority/3, area/all

#57 Set appropriate actions permissions for build job.
  .github/workflow-gen/Program.cs
  .github/workflows/access-token-management-ci.yml
  .github/workflows/identity-model-ci.yml
  .github/workflows/identity-model-oidc-client-ci.yml
  .github/workflows/ignore-this-ci.yml
Labels: priority/2, area/all

#56 Mark DateTimeExtensions methods as obsolete
  identity-model/src/IdentityModel/DateTimeExtensions.cs
Labels: area/identity-model, priority/3, impact/non-breaking

#54 Pin GHA dependencies
  .github/workflow-gen/Program.cs
  .github/workflows/access-token-management-ci.yml
  .github/workflows/access-token-management-release.yml
  .github/workflows/codeql.yml
  .github/workflows/identity-model-ci.yml
  .github/workflows/identity-model-oidc-client-ci.yml
  .github/workflows/identity-model-oidc-client-release.yml
  .github/workflows/identity-model-release.yml
  .github/workflows/ignore-this-ci.yml
  .github/workflows/ignore-this-release.yml
Labels: priority/3, impact/non-breaking, dependencies, area/all
