Repository DuendeSoftware/foss, pull requests merged in 2025-01, with the labels that each got.

#86 Replace FluentAssertions with Shouldly
  Directory.Packages.props
  access-token-management/test/AccessTokenManagement.Tests/Usings.cs
  identity-model-oidc-client/test/IdentityModel.OidcClient.Tests/AuthorizeRequestTests.cs
  identity-model-oidc-client/test/IdentityModel.OidcClient.Tests/CodeFlowResponseTests.cs
  identity-model-oidc-client/test/IdentityModel.OidcClient.Tests/CommonResponseTests.cs
  identity-model-oidc-client/test/IdentityModel.OidcClient.Tests/ConfigurationTests.cs
  identity-model-oidc-client/test/IdentityModel.OidcClient.Tests/CryptoHelperTests.cs
  identity-model-oidc-client/test/IdentityModel.OidcClient.Tests/DPoP/DPoPTests.cs
  identity-model-oidc-client/test/IdentityModel.OidcClient.Tests/EndSessionUrlTests.cs
  identity-model-oidc-client/test/IdentityModel.OidcClient.Tests/IdentityModel.OidcClient.Tests.csproj
  identity-model-oidc-client/test/IdentityModel.OidcClient.Tests/LogSerializerTests.cs
  identity-model-oidc-client/test/IdentityModel.OidcClient.Tests/OidcClientTests.cs
  identity-model-oidc-client/test/IdentityModel.OidcClient.Tests/RefreshTokenDelegatingHandlerTests.cs
  identity-model/test/IdentityModel.Tests/AuthorizeResponseTests.cs
  identity-model/test/IdentityModel.Tests/BasicAuthenticationEncodingTests.cs
  identity-model/test/IdentityModel.Tests/ClaimsComparisonTests.cs
  identity-model/test/IdentityModel.Tests/DiscoveryCacheTests.cs
  identity-model/test/IdentityModel.Tests/DiscoveryPolicyTestsBase.cs
  identity-model/test/IdentityModel.Tests/DiscoveryPolicyTests_AuthorityStringComparison.cs
  identity-model/test/IdentityModel.Tests/DiscoveryPolicyTests_AuthorityUriComparison.cs
  identity-model/test/IdentityModel.Tests/DiscoveryPolicyTests_WithoutAuthorityValidation.cs
  identity-model/test/IdentityModel.Tests/GlobalUsings.cs
  identity-model/test/IdentityModel.Tests/HttpClientExtensions/CibaExtensionsTests.cs
  identity-model/test/IdentityModel.Tests/HttpClientExtensions/DeviceAuthorizationExtensionsTests.cs
  identity-model/test/IdentityModel.Tests/HttpClientExtensions/DiscoveryExtensionsTests.cs
  identity-model/test/IdentityModel.Tests/HttpClientExtensions/DynamicClientRegistrationTests.cs
  identity-model/test/IdentityModel.Tests/HttpClientExtensions/HttpRequestMethodExtensions.cs
  identity-model/test/IdentityModel.Tests/HttpClientExtensions/JsonWebKeyExtensionsTests.cs
  identity-model/test/IdentityModel.Tests/HttpClientExtensions/PushedAuthorizationTests.cs
  identity-model/test/IdentityModel.Tests/HttpClientExtensions/TokenIntrospectionTests.cs
  identity-model/test/IdentityModel.Tests/HttpClientExtensions/TokenRequestExtensionsRequestTests.cs
  identity-model/test/IdentityModel.Tests/HttpClientExtensions/TokenRequestExtensionsResponseTests.cs
  identity-model/test/IdentityModel.Tests/HttpClientExtensions/TokenRevocationExtensions.cs
  identity-model/test/IdentityModel.Tests/HttpClientExtensions/UserInfoExtensionsTests.cs
  identity-model/test/IdentityModel.Tests/IdentityModel.Tests.csproj
  identity-model/test/IdentityModel.Tests/Infrastructure/NetworkHandler.cs
  identity-model/test/IdentityModel.Tests/Internal/ParametersTest.cs
  identity-model/test/IdentityModel.Tests/RequestUrlTests.cs
  identity-model/test/IdentityModel.Tests/ShouldlyExtensions.cs
  identity-model/test/IdentityModel.Tests/TokenClientRequestTests.cs
Labels: priority/2, impact/non-breaking, area/all

#87 Upgrade to xunit.v3
  Directory.Packages.props
  identity-model-oidc-client/test/IdentityModel.OidcClient.Tests/RefreshTokenDelegatingHandlerTests.cs
  identity-model/test/IdentityModel.Tests/IdentityModel.Tests.csproj
  identity-model/test/IdentityModel.Tests/Verifications/PublicApiVerificationTests.VerifyPublicApi.verified.txt
  test.props
Labels: impact/non-breaking, area/all

#88 Fix typo in environment variable key for DOTNET_NOLOGO
  .github/workflow-gen/Program.cs
  .github/workflows/access-token-management-ci.yml
  .github/workflows/access-token-management-release.yml
  .github/workflows/identity-model-ci.yml
  .github/workflows/identity-model-oidc-client-ci.yml
  .github/workflows/identity-model-oidc-client-release.yml
  .github/workflows/identity-model-release.yml
  .github/workflows/ignore-this-ci.yml
  .github/workflows/ignore-this-release.yml
Labels: priority/3, impact/non-breaking, area/all
