Repository DuendeSoftware/foss, pull requests merged in 2025-02, with the labels that each got.

#90 atm - Make sure sync method of access token handler is not invoked
  access-token-management/src/AccessTokenManagement/AccessTokenHandler.cs
Labels: area/access-token-management, impact/non-breaking

#91 atm - Make ClientCredentialsTokenManagementBuilder.Services a public property
  access-token-management/src/AccessTokenManagement/ClientCredentialsTokenManagementBuilder.cs
Labels: area/access-token-management, impact/non-breaking

#92 build - don't use pull_request_target anymore
  .github/workflow-gen/Program.cs
  .github/workflow-gen/Properties/launchSettings.json
  .github/workflows/access-token-management-ci.yml
  .github/workflows/access-token-management-release.yml
  .github/workflows/identity-model-ci.yml
  .github/workflows/identity-model-oidc-client-ci.yml
  .github/workflows/identity-model-oidc-client-release.yml
  .github/workflows/identity-model-release.yml
  .github/workflows/ignore-this-ci.yml
  .github/workflows/ignore-this-release.yml
Labels: impact/non-breaking, area/all

#94 bump scorecard package versions to resolve issues with build.
  .github/workflows/scorecard.yml
Labels: impact/non-breaking, area/all

#97 Fix docs link on readme
  access-token-management/README.md
Labels: area/access-token-management

#100 Change condition to run step if workflow dispatch as well as push.
  .github/workflow-gen/Program.cs
  .github/workflows/access-token-management-ci.yml
  .github/workflows/access-token-management-release.yml
  .github/workflows/identity-model-ci.yml
  .github/workflows/identity-model-oidc-client-ci.yml
  .github/workflows/identity-model-oidc-client-release.yml
  .github/workflows/identity-model-release.yml
  .github/workflows/ignore-this-ci.yml
  .github/workflows/ignore-this-release.yml
Labels: priority/2, area/all

#101 Always sign packages in release workflow
  .github/workflow-gen/Program.cs
  .github/workflows/access-token-management-ci.yml
  .github/workflows/access-token-management-release.yml
  .github/workflows/identity-model-ci.yml
  .github/workflows/identity-model-oidc-client-ci.yml
  .github/workflows/identity-model-oidc-client-release.yml
  .github/workflows/identity-model-release.yml
  .github/workflows/ignore-this-ci.yml
  .github/workflows/ignore-this-release.yml
Labels: priority/2, area/all

#102 fix test failing in ncrunch
  access-token-management/test/AccessTokenManagement.Tests/StoreTokensInAuthenticationPropertiesTests.cs
Labels: priority/4

#99 Ev/build split publish test
  .github/workflow-gen/Program.cs
  .github/workflows/access-token-management-ci.yml
  .github/workflows/access-token-management-release.yml
  .github/workflows/generate-test-reports.yml
  .github/workflows/identity-model-ci.yml
  .github/workflows/identity-model-oidc-client-ci.yml
  .github/workflows/identity-model-oidc-client-release.yml
  .github/workflows/identity-model-release.yml
  .github/workflows/ignore-this-ci.yml
  .github/workflows/ignore-this-release.yml
Labels: priority/3, impact/non-breaking, area/all

#104 Fix workflow for generating test reports
  .github/workflow-gen/Program.cs
  .github/workflows/generate-test-reports.yml
  access-token-management/src/AccessTokenManagement/Interfaces/ITokenRequestSynchronization.cs
Labels: area/all

#105 Build - Add capability to release from target branch
  .github/workflow-gen/Program.cs
  .github/workflows/access-token-management-release.yml
  .github/workflows/identity-model-oidc-client-release.yml
  .github/workflows/identity-model-release.yml
  .github/workflows/ignore-this-release.yml
Labels: impact/non-breaking, area/all

#106 fix issue with workflow gen program that version input was missing
  .github/workflow-gen/Program.cs
  .github/workflows/access-token-management-release.yml
  .github/workflows/identity-model-oidc-client-release.yml
  .github/workflows/identity-model-release.yml
  .github/workflows/ignore-this-release.yml
Labels: impact/non-breaking, area/all

#107 Migrate sln to slnx
  foss.sln
  foss.slnx
Labels: priority/3, area/all

#109 Pin github actions checkout version
  .github/workflow-gen/Program.cs
  .github/workflows/access-token-management-ci.yml
  .github/workflows/identity-model-ci.yml
  .github/workflows/identity-model-oidc-client-ci.yml
  .github/workflows/ignore-this-ci.yml
Labels: priority/3, area/all

#108 Remove secitgo cert file
  .github/workflow-gen/Program.cs
  .github/workflows/SectigoPublicCodeSigningRootCrossAAA.crt
  .github/workflows/access-token-management-release.yml
  .github/workflows/identity-model-oidc-client-release.yml
  .github/workflows/identity-model-release.yml
  .github/workflows/ignore-this-release.yml
Labels: priority/3, area/all

#111 Release of Duende.AccessTokenManagement 3.2.0
  .github/workflow-gen/Program.cs
  .github/workflows/access-token-management-release.yml
  .github/workflows/identity-model-oidc-client-release.yml
  .github/workflows/identity-model-release.yml
  .github/workflows/ignore-this-release.yml
  access-token-management/src/AccessTokenManagement/ClientCredentialsTokenManagementService.cs
  access-token-management/src/AccessTokenManagement/DistributedClientCredentialsTokenCache.cs
  access-token-management/src/AccessTokenManagement/Interfaces/IClientCredentialsTokenCache.cs
  access-token-management/test/AccessTokenManagement.Tests/BackChannelClientTests.cs
Labels: area/access-token-management, impact/breaking

#113 Add bug report template.
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: area/all

#114 Drop duplicate issue creation entry in GH
  .github/ISSUE_TEMPLATE/config.yml
Labels: area/all

#116 Update readme
  README.md
Labels: area/all

#118 Revert "Migrate sln to slnx"
  foss.sln
  foss.slnx
Labels: area/all

#120 Move `global.json` to root directory
  access-token-management/global.json
  foss.sln
  global.json
Labels: area/all

#112 Make DPOP Nonce header search case insensitive
  access-token-management/src/AccessTokenManagement/DPoPExtensions.cs
  access-token-management/test/AccessTokenManagement.Tests/DPoPExtensionTests.cs
  identity-model-oidc-client/src/IdentityModel.OidcClient.Extensions/DPoP/DPoPExtensions.cs
  identity-model-oidc-client/test/IdentityModel.OidcClient.Tests/DPoPExtensionTests.cs
Labels: area/access-token-management, area/identity-model-oidc-client

#103 Update OidcClient samples for .NET 9
  .vscode/launch.json
  .vscode/tasks.json
  access-token-management/samples/BlazorServer/BlazorServer.csproj
  access-token-management/samples/BlazorServer/Pages/Index.razor
  access-token-management/samples/Web/Controllers/HomeController.cs
  access-token-management/samples/Web/Startup.cs
  access-token-management/samples/Web/Views/Home/Index.cshtml
  access-token-management/samples/Web/Views/Home/Secure.cshtml
  access-token-management/samples/Web/Web.csproj
  access-token-management/samples/Web/appsettings.json
  access-token-management/samples/WebJarJwt/WebJarJwt.csproj
  access-token-management/samples/Worker/Worker.csproj
  access-token-management/samples/WorkerDI/WorkerDI.csproj
  access-token-management/test/AccessTokenManagement.Tests/UserTokenManagementTests.cs
  identity-model-oidc-client/.gitignore
  identity-model-oidc-client/.vscode/launch.json
  identity-model-oidc-client/.vscode/tasks.json
  identity-model-oidc-client/clients/ConsoleClientWithBrowser/ConsoleClientWithBrowser.csproj
  identity-model-oidc-client/clients/ConsoleClientWithBrowser/Program.cs
  identity-model-oidc-client/clients/ConsoleClientWithBrowser/SystemBrowser.cs
  identity-model-oidc-client/clients/ConsoleClientWithBrowserAndDPoP/ConsoleClientWithBrowserAndDPoP.csproj
  identity-model-oidc-client/clients/ConsoleClientWithBrowserAndDPoP/Program.cs
  identity-model-oidc-client/clients/ConsoleClientWithBrowserAndDPoP/SystemBrowser.cs
  identity-model-oidc-client/clients/ManualModeConsoleClient/ManualModeConsoleClient.csproj
  identity-model-oidc-client/clients/ManualModeConsoleClient/Program.cs
  identity-model-oidc-client/samples/HttpSysConsoleClient/.vscode/launch.json
  identity-model-oidc-client/samples/HttpSysConsoleClient/.vscode/tasks.json
  identity-model-oidc-client/samples/HttpSysConsoleClient/ConsoleSystemBrowser.sln
  identity-model-oidc-client/samples/HttpSysConsoleClient/HttpSysConsoleClient/HttpSysConsoleClient.csproj
  identity-model-oidc-client/samples/HttpSysConsoleClient/HttpSysConsoleClient/Program.cs
  identity-model-oidc-client/samples/Maui/MauiApp1/MauiApp1/MainPage.xaml.cs
  identity-model-oidc-client/samples/Maui/MauiApp1/MauiApp1/MauiApp1.csproj
  identity-model-oidc-client/samples/Maui/MauiApp1/MauiApp1/MauiAuthenticationBrowser.cs
  identity-model-oidc-client/samples/Maui/MauiApp1/MauiApp1/MauiProgram.cs
  identity-model-oidc-client/samples/Maui/README.md
  identity-model-oidc-client/samples/NetCoreConsoleClient/.vscode/launch.json
  identity-model-oidc-client/samples/NetCoreConsoleClient/.vscode/tasks.json
  identity-model-oidc-client/samples/NetCoreConsoleClient/src/NetCoreConsoleClient/NetCoreConsoleClient.csproj
  identity-model-oidc-client/samples/NetCoreConsoleClient/src/NetCoreConsoleClient/Program.cs
  identity-model-oidc-client/samples/NetCoreConsoleClient/src/NetCoreConsoleClient/SystemBrowser.cs
  identity-model-oidc-client/samples/WinFormsWebView2/WinFormsWebView2/Form1.cs
  identity-model-oidc-client/samples/WinFormsWebView2/WinFormsWebView2/WinFormsWebView.cs
  identity-model-oidc-client/samples/WinFormsWebView2/WinFormsWebView2/WinFormsWebView2.csproj
  identity-model-oidc-client/samples/WindowsConsoleSystemBrowser/WindowsConsoleSystemBrowser/Program.cs
  identity-model-oidc-client/samples/WindowsConsoleSystemBrowser/WindowsConsoleSystemBrowser/WindowsConsoleSystemBrowser.csproj
  identity-model-oidc-client/samples/Wpf/Wpf/App.xaml.cs
  identity-model-oidc-client/samples/Wpf/Wpf/MainWindow.xaml.cs
  identity-model-oidc-client/samples/Wpf/Wpf/Session.cs
  identity-model-oidc-client/samples/Wpf/Wpf/Wpf.csproj
  identity-model-oidc-client/samples/WpfWebView2/WpfWebView2/MainWindow.xaml.cs
  identity-model-oidc-client/samples/WpfWebView2/WpfWebView2/WpfEmbeddedBrowser.cs
  identity-model-oidc-client/samples/WpfWebView2/WpfWebView2/WpfWebView2.csproj
Labels: area/access-token-management, area/identity-model-oidc-client

#123 Add codeowners
  .github/CODEOWNERS
Labels: area/all

#122 Use headers TryGetValues which is already case in-sensitive
  access-token-management/src/AccessTokenManagement/DPoPExtensions.cs
  identity-model-oidc-client/src/IdentityModel.OidcClient.Extensions/DPoP/DPoPExtensions.cs
Labels: area/access-token-management, priority/3, impact/non-breaking
